# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Live Query Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BasicUserRegistration-Swift
  pod 'ParseLiveQuery', git: 'https://github.com/parseplatform/ParseLiveQuery-iOS-OSX', branch: "fix-object-decoding"
end
